### ISSUE TITLE
Mesh?

### ISSUE THREAD

**Issue by aldanor** [not-fl3/good-web-game#20]
First thanks for the nice lib :) Wondering, any chance of porting `graphics::mesh` over?

**Comment by not-fl3** [comment]
> First thanks for the nice lib :) Wondering, any chance of porting `graphics::mesh` over?

Hi! I made an attempt to implement meshes once: https://gist.github.com/not-fl3/524185786aa7c059f355affc479c1996
It worked pretty good, but was not api-compatible with ggez. This may be used as a reference for `graphics::mesh` implementeation PR ;)

**Comment by not-fl3** [comment]
Mesh API is implemented now!

**Comment by aldanor** [comment]
@not-fl3 That's fantastic, thanks!
