### ISSUE TITLE
Better font rendering?

### ISSUE THREAD

**Issue by canadaduane** [not-fl3/good-web-game#22]
The current demo displays the Level and Score as poorly rendered DejaVuSerif:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/129/72575266-0c85ed00-3889-11ea-90a5-1ad017b7bff0.png">

Is this something on the radar to be fixed later?

**Comment by PSteinhaus** [comment]
Since good-web-game now uses the same text rendering as ggez (and the same font) I think it's ok to close this.
