### ISSUE TITLE
LinkError when running in browser

### ISSUE THREAD

**Issue by adambiltcliffe** [not-fl3/good-web-game#44]
After successfully building the examples on the wasm32-unknown-unknown target and serving them alongside the .html file from the miniquad readme (which appears to be the correct way to deploy to web according to the current instructions) I get the following error in the browser (Chrome):

`Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #57 module="env" function="time" error: function import requires a callable`

The examples from miniquad itself work fine following the same process.

**Comment by adambiltcliffe** [comment]
Is this related to this? https://github.com/not-fl3/miniquad/commit/a36e05300f8c59fc2fbbe1747324d2f44ba8b81b

**Comment by adambiltcliffe** [comment]
Modifying the gl.js provided with miniquad to provide an import for 'time' instead of 'now' gets this working, but a more robust fix is probably needed.

**Comment by not-fl3** [comment]
`good-web-game` should update to the fresh miniquad version to use lasted gl.js
Workaround right now - use the link to gl.js with a versoin:
    <script src="https://not-fl3.github.io/miniquad-samples/gl-0.2.54.js"></script>

**Comment by not-fl3** [comment]
Relevant miniquad PR: https://github.com/not-fl3/miniquad/pull/97
I believe in the near future we will be able to avoid manually update gl.js version. But right now it is a problem - you either need to host and update appropriate gl.js version(or use the one from miniquad-samples, but with appropriate version)
Or always update miniquad and use the latest gl.js. 
However I think the best place to continue this discussion is in the linked miniquad's PR. 

Fill free to reopen if the workaround with the version did not fix the problem!

**Comment by TuntematonSotilas** [comment]
Hello what is the apporpriate version of gl.js for
macroquad = "0.2.9"
?

**Comment by not-fl3** [comment]
> Hello what is the apporpriate version of gl.js for
> macroquad = "0.2.9"
> ?
> 
> If I use
> `<script src="https://not-fl3.github.io/miniquad-samples/gl.js"></script>`
> Then I got :
> `LinkError: WebAssembly.instantiate(): Import #72 module="env" function="__web_on_grow" error: function import requires a callable `

https://not-fl3.github.io/miniquad-samples/gl-0.1.19.js worked for me with macroquad 0.2
