### ISSUE TITLE
How to log message in wasm?

### ISSUE THREAD

**Issue by yanganto** [not-fl3/good-web-game#47]
Hi, 

Thanks for building goog-web-game, this project is really cool.

I try to use this framework to learn more about game development and wasm, but I can not find a correct way to log the message into the console.

In the picture of Readme, I should use [sapp-console-log](https://github.com/canadaduane/sapp-console-log) to log things.

Is that log crate ready to use?  Or something I may help with this.

Thanks.

ref: https://github.com/yanganto/rust-wasm-sokoban/issues/5

**Comment by not-fl3** [comment]
I would recommend to use `log-impl` feature from `good-web-game` and use `warn!` `error!` etc macros just from gwg.

Something like this: 
in Cargo.toml
```
good-web-game = { version = "0.3", features = ["log-impl"] }
```

in your code

```
use good_web_game::warn;

..
warn!("message");
```

**Comment by yanganto** [comment]
Thanks for explaining in detail.
